{
 "title": "Supervision - NTP Copy",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "IT",
    "label": "Summarize",
    "query": "10s,20s,30s,1m,5m,7m,10m,15m,20m,30m,1h,6h,12h,1d,18h,2d,3d,4d,5d,6d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Nb de Requêtes NTP par seconde",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"DB_MAISON\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Mesures\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Nb_NTP_Requests\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"NTP01\")\r\n  |> derivative(unit: 1s, nonNegative: true, columns: [\"_value\"], timeColumn: \"_time\")\r\n  |> aggregateWindow(every: ${IT}, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "NTP - GPS lock time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Mesures",
     "query": "from(bucket: \"DB_MAISON\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Mesures\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"GPS_lock_time\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"NTP01\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "GPS_lock_time" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "NTP01" }
     ]
    }
   ]
  },
  {
   "title": "NTP - Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Mesures",
     "query": "from(bucket: \"DB_MAISON\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Mesures\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Uptime\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "Uptime" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "NTP01" }
     ]
    }
   ]
  },
  {
   "title": "NTP Requetes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Mesures",
     "query": "from(bucket: \"DB_MAISON\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Mesures\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Nb_NTP_Requests\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"NTP01\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "Nb_NTP_Requests" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "NTP01" }
     ]
    }
   ]
  },
  {
   "title": "NTP - Nb de SAT",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$IT" ], "type": "time" }
     ],
     "measurement": "Mesures",
     "query": "from(bucket: \"DB_MAISON\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Mesures\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Nb_de_SAT\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"NTP01\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "Nb_de_SAT" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "NTP01" }
     ]
    }
   ]
  },
  {
   "title": "Nb de SAT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 6 },
   "targets": [
    {
     "query": "from(bucket: \"DB_MAISON\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Mesures\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Nb_de_SAT\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"NTP01\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "ntppool status",
   "type": "text",
   "description": "The Score graph - Blue/red \"double size\" dots are points/scores (using the right axis). A couple of times an hour the pool system checks the time from your server and compares it to the local time. Points are deducted if the server can’t be reached or if the time offset is more than 100ms (as measured from the monitoring systems). More points are deducted the bigger the offset is.\n\n\nThe Offset graph - Green/orange/red small dots are offsets (in milliseconds, using the left axis). The monitoring system works roughly like an SNTP (RFC 2030) client, so it is more susceptible by random network latencies between the server and the monitoring system than a regular ntpd server would be.\n\nThe monitoring system can be inaccurate as much as 10ms or more.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "options": {
    "content": "<a href=\"http://www.pool.ntp.org/scores/$ip\">\n  <img src=\"http://graphs.ntppool.net/graph/$ip/offset.png\" style=\"margin:0 auto; display:block\">\n</a>"
   }
  }
 ]
}